Update pagina_login.dart
anotherlusitano/ESTG-ES1-Chat-Together pull request #30
Opened 2024-05-22 11:54 UTC by antonuolink

This fixes #3

2024-05-22 12:16 UTC, anotherlusitano requested changes
Está no bom caminho mas é preciso melhorar umas quantas coisas, e também tirar os comentários.

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +}
Este bloco não devia existir, é suposto chamarmos a página `LoginScreen` através do `main.dart`.

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +}
Este bloco também não devia existir, já que temos o `BotaoPrincipal` no `botao_principal.dart`.

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +              ),
Substitui isto pelo widget `BotaoPrincipal` dentro do ficheiro `lib/widgets/botao_principal.dart`.
E deixa a função como nula

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +        child: SingleChildScrollView(
Acho que este widget não é necessário

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +class LoginScreen extends StatefulWidget {
Muda o nome do widget para `PaginaLogin`, como no nome do ficheiro

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +            mainAxisAlignment: MainAxisAlignment.center,
Isto é mesmo necessário se já tivermos o widget encapsulado dentro do `Center`?

2024-05-22 12:16 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +              ),
Isto está muito emaranhado, poderia apenas ser dois widgets, `Text` e `TextButton`.
E a função seria nula.

2024-05-22 12:18 UTC, anotherlusitano commented
E tenta também por as screenshots, da página e do Figma, na descrição

2024-06-04 10:10 UTC, anotherlusitano approved these changes
odeio a bagunça que o código está mas não temos muitas opções

2024-06-04 10:11 UTC, xXD4rkSoulXx approved these changes

2024-06-04 10:12 UTC, merged