Update pagina_sign_up.dart
anotherlusitano/ESTG-ES1-Chat-Together pull request #31
Opened 2024-05-23 09:09 UTC by Afonso295

This Fixes #4

2024-05-25 11:21 UTC, anotherlusitano requested changes
Ve os comentários que eu escrevi na #30

2024-05-25 11:21 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +}
Não precisamos disto

2024-05-25 11:21 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +}
Não era preciso separar o BotaoVoltar para ser um widget próprio, já que só vai ser utilizado uma vez no programa, e não tem muitas linhas de código

2024-05-25 11:21 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +}
Nós já temos esse widget criado

2024-05-25 11:21 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +                    },
Podias só por `null`

2024-05-25 11:21 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +                    }),
Tratamos da navegação depois, por agora põe `null`

2024-05-29 20:14 UTC, anotherlusitano requested changes

2024-05-29 20:14 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +class _LoginScreenState extends State<LoginScreen> {
Eu gostaria muito de saber o porquê disto se chamar `LoginScreen` quando estás a fazer a `SignUpScreen` :thinking:

2024-06-06 12:33 UTC, antonuolink approved these changes
esta bom

2024-06-06 12:33 UTC, anotherlusitano approved these changes
LGTM

2024-06-06 12:34 UTC, merged