Update pagina_home.dart
anotherlusitano/ESTG-ES1-Chat-Together pull request #32
Opened 2024-05-25 12:54 UTC by xXD4rkSoulXx

Thix fixes #5

2024-05-29 20:19 UTC, anotherlusitano requested changes
![your code](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMGtzYTBiN3Z1bXAzdzQ0b2dtcXY4b3JqY3I3YnlqNThmdXJ0OXIxOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6SusuSNhp0B7a/giphy.gif)

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +//import ""; //Página Mensagens
Comentários desnecessários :smile:

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +}
Isto já existe no `main.dart`

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                                                                        );*/
E que tal não teres estes comentários e deixares `null` ?

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                                                        );*/
E que tal deixar isto `null` para a próxima tarefa?

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +              //O código dentro Expanded já é a parte normal do site, com a logo, o Bem-vindo e isso tudo
Então separa em um widget só, porque vais usa-lo na página dos amigos

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                                                            */
```Java
public void onPressed(Funcao funcao) {
    if(funcao == null) {
       // Lider contente
    } else {
       // Apagar comentários e deixa-la null
    }
}
```

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                    //O código dentro deste Padding são os botões de Mensagens e Pedidos
//O comentário dentro deste código é apenas para preencher espaço

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                                                  });
Código não necessário, mete `null`

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                                                }),
```Java
if onPressed() == null {
  Boss.Happy = True;
}
  ```

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                      //O código dentro deste Expanded é a parte do código em que aparece a lista de pedidos de amizade
Então separa no seu próprio widget

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +                      //O código dentro deste Expanded é caso não haja pedidos de amizades
Deu para perceber pelo `quantidade_utilizadores == 0`, apesar que podia ser `quantidade_pedidos`

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +  ];
![My answer to this code](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2tvM2dqbTVwOXRneTR1eXpnaDdrNXg1OWhtcTZ6d3BsenNneGpwOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xULW8N9O5WD32L5052/giphy.gif)

2024-05-29 20:19 UTC, anotherlusitano commented on lib/paginas/pagina_home.dart
> +class Pagina_HomeEstado extends State<Pagina_Home> {
Por favor apaga o underscore do nome das classes....

2024-05-31 19:41 UTC, anotherlusitano commented
No ficheiro `main.dart` ainda está na nomenclatura antiga:
```dart
void main() {
  runApp(const Pagina_Home());
}
```

2024-06-04 12:53 UTC, anotherlusitano approved these changes
I just dont care anymore

2024-06-04 12:56 UTC, Afonso295 approved these changes
🗑️ 🤡

2024-06-04 12:57 UTC, merged