Criar Página de Mensagens
anotherlusitano/ESTG-ES1-Chat-Together pull request #37
Opened 2024-05-28 22:21 UTC by xXD4rkSoulXx

This fixes #36 

![image](https://github.com/anotherlusitano/ESTG-ES1-Chat-Together/assets/60749477/c7a6aa4a-3ffc-4cac-9e04-bdfd297b24bd)
![image](https://github.com/anotherlusitano/ESTG-ES1-Chat-Together/assets/60749477/ba3194a1-79f9-450a-b6f4-e021bd1ce3ac)
![image](https://github.com/anotherlusitano/ESTG-ES1-Chat-Together/assets/60749477/400b54aa-4fea-456b-9020-50e79b113393)
![image](https://github.com/anotherlusitano/ESTG-ES1-Chat-Together/assets/60749477/a1b0e065-d992-4711-b5cb-f3a3071644df)

2024-05-29 19:51 UTC, anotherlusitano requested changes
This is so much spaghetti code that I'm afraid that we will not be able to finish this task in time :pensive:

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +//import ""; //Página Home
Isto não é preciso

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +}
Isto é suposto estar no ficheiro `main.dart`, para podermos testar a página, ou então quando a página do Login estiver feita por a navegação para aqui

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +}
Umas coisas que podiam ser melhoradas:
- O widget podia estar no seu próprio ficheiro na pasta `widgets`
- Já que o widget é uma mensagem, faz sentido chamar-se `Mensagem`
- Era apenas preciso fazer a UI do widget, e não a funcionalidade

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                                                            );*/
Tira os comentários e põe null porque nós, neste momento, nem iniciar sessão temos

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                  ])
Não entendi o porquê deste código repetido

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                                                  });
A formatação da data está maior que sei lá o que...
E é suposto fazeres a UI da página e não uma funcionalidade "falsa", apenas põe `null` nisso e depois tratamos disto

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +  ];
Isto não era necessário e só tiveste mais trabalho

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                          //Mostra todos os amigos
Os comentários não são necessários apartir do momento que temos uma variável chamada `quantidade_amigos` que pode ser zero ou mais

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                                          });
Mais uma vez, isto é desnecessário e devia ser `null`
Nós depois iremos criar uma issue para resolver isso

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                                            (value) //Se clicar Enter ao enviar a mensagem
Se os nomes das variáveis são explicitos, não é preciso ter comentários a explicar o que elas fazem

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                      //Caixa de texto
![image](https://github.com/anotherlusitano/ESTG-ES1-Chat-Together/assets/108989500/b1944590-8aa7-45fb-aaf5-26a7322682e1)

Caixa de texto

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                if (utilizador_selecionado != 0)
O utilizador nunca vai ser "não selecionado" porque é preciso ele logar na conta para poder se quer entrar nesta página

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                      //Tela inicial, quando não tenho amigos ou não cliquei em nenhum amigo, aparece a logo e o Bem vindo
Bem vindo
Esta tela vai sempre aparecer assim que entras, ela só muda quando clicas em algum amigo

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                            })),
Como eu adoro um amontuado de `if` statements que não vão ser necessários :)

Basicamente só vai haver um `if` statement, que é no inicio do método `build`, onde vai fazer uma requisição à tabela `mensagens` e se tiver algo vai fazer isto tudo, e se não tiver apenas devolve o que é para devolver

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                                                            */
Mais uma vez, deixa `null` porque isto é uma tarefa à parte

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                    //Ícones de mensagem e pedidos de amizade
Comentário bueda fixe :+1: 

**Apaga**

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                          })),
Divide isto no seu próprio widget, chamado `ItemAmigo` ou outro nome melhor, onde vai receber como parametro o nome do amigo e uma função

2024-05-29 19:51 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +}
Apaga isto, **AGORA**

2024-05-31 17:30 UTC, xXD4rkSoulXx commented on lib/paginas/pagina_mensagens.dart
> +                  ])
Porque um dos botões logout, o anterior, é para quando está junto com a caixa de texto lá das mensagens. Este é o botão de logout na parte inicial quando ainda não selecionei nenhum amigo que queira conversar. Sem essas repetições, a caixa de texto fica desformatada.
E já apaguei esse comentário.

2024-05-31 17:33 UTC, xXD4rkSoulXx commented on lib/paginas/pagina_mensagens.dart
> +                                                  });
A formatação da data é mesmo necessário estar assim para ficar dia, mês, ano, hora e segundo alinhado no formato correto. Tal como está no código que me mostraste no outro dia, foi aí que tirei a referência.
Já apaguei.

2024-05-31 17:38 UTC, xXD4rkSoulXx commented on lib/paginas/pagina_mensagens.dart
> +                      //Caixa de texto
Caixa de texto, traduzido da palavra Textbox, é onde o utilizador escreve as mensagens, tal como esta caixa de texto que estou a utilizar neste devido momento para comentar devolta.

2024-05-31 17:40 UTC, xXD4rkSoulXx commented on lib/paginas/pagina_mensagens.dart
> +                      //Tela inicial, quando não tenho amigos ou não cliquei em nenhum amigo, aparece a logo e o Bem vindo
Mas são duas páginas diferentes, quando clico no ícone dos pedidos de amizade, vai para uma página, quando clico no ícone das mensagens, vai para outra. O máximo que posso fazer é tentar criar uma função externa para reutilizar esse código.

2024-05-31 17:40 UTC, anotherlusitano commented on lib/paginas/pagina_mensagens.dart
> +                      //Caixa de texto
O que eu queria dizer era que não fazia sentido o comentário estar ali

2024-05-31 17:44 UTC, xXD4rkSoulXx commented on lib/paginas/pagina_mensagens.dart
> +                if (utilizador_selecionado != 0)
Eu já troquei o nome da variável para amigo_selecionado para ser mais fácil de se perceber. A intenção era ver se o utilizador tem amigos ou não.

2024-05-31 17:47 UTC, xXD4rkSoulXx commented on lib/paginas/pagina_mensagens.dart
> +                            })),
Mas o resultado dessa requisição deve ficar guardado numa variável calculo eu, para verificar como vai ficar o layout, se aparece mensagens ou sem mensagens e essas coisas. Os ifs vão ser necessários de qualquer das formas.

2024-06-04 12:58 UTC, anotherlusitano approved these changes
I want to die

2024-06-04 13:00 UTC, Afonso295 approved these changes
A chuva vai seguir-te até perceberes que tu és a chuva, pensa nisso. 😏

2024-06-04 13:00 UTC, merged