Update pagina_login.dart
anotherlusitano/ESTG-ES1-Chat-Together pull request #38
Opened 2024-06-06 13:02 UTC by antonuolink

This fixes #9

2024-06-06 13:04 UTC, Afonso295 reviewed
acho que concordo com o João

2024-06-06 13:05 UTC, anotherlusitano requested changes
MALDITO CHATGPT

2024-06-06 13:05 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +import 'pagina_sign_up.dart';
Isto está errado! O programa não consegue identificar a localização da página de sign up, tens de `package:gaming_together/paginas/pagina_sign_up.dart`

2024-06-06 13:05 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +                    );
Volta ao que estava antes, porque não temos a página home

2024-06-06 13:05 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +
Retira esta linha branca

2024-06-06 13:42 UTC, anotherlusitano commented
Só digo isto:
> Error: The method '_PaginaSignUp' isn't defined for the class 'PaginaSignUp'.
>- 'PaginaSignUp' is from 'package:gaming_together/paginas/pagina_sign_up.dart' ('lib/paginas/pagina_sign_up.dart').
>  _PaginaSignUpState createState() => _PaginaSignUp();
>                                      ^^^^^^^^^^^^^
>lib/paginas/pagina_sign_up.dart:33:14:
>Error: The getter 'onTap' isn't defined for the class '_PaginaSignUpState'.
 >- '_PaginaSignUpState' is from 'package:gaming_together/paginas/pagina_sign_up.dart' ('lib/paginas/>pagina_sign_up.dart').
 >     onTap: onTap,
  >           ^^^^^

2024-06-11 10:19 UTC, anotherlusitano approved these changes
:taco:

2024-06-11 10:19 UTC, anotherlusitano commented on lib/paginas/pagina_login.dart
> +                            MaterialPageRoute(builder: (context) => PaginaSignUp()),
Ta certo

2024-06-11 10:19 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +  _PaginaSignUpState createState() => _PaginaSignUpState();
Quem foi o otário que fez isto?

2024-06-11 10:19 UTC, anotherlusitano commented on lib/paginas/pagina_sign_up.dart
> +      onTap: null,
:on: tap

2024-06-11 10:20 UTC, xXD4rkSoulXx approved these changes
Menino António precisa de aprender a programar melhor :D

2024-06-11 10:20 UTC, merged

2024-06-13 08:51 UTC, anotherlusitano commented
Expliquem-me porque esta pull request chama-se "Update pagina_login" e não "Adicionar Navegação"
E mais, porque raios não existe o resto das navegações?